shared:
    image: node:6

jobs:
    main:
        steps:
            - set0: meta set dirs {}
    publish:
        steps:
            - get: meta get dirs
    job3:
        steps:
            - echo: echo blah
    job4:
        steps:
            - echo: echo bye
