shared:
    image: node:6

jobs:
    main:
        steps:
            - set0: meta set dirs {}
            - set: meta set dirs.foo true
            - set2: meta set dirs.bar false
    publish:
        steps:
            - get: meta get dirs
