shared:
    image: node:12

jobs:
    main:
        environment:
            SD_SONAR_OPTS: "-Dsonar.sources=lib -Dsonar.javascript.lcov.reportPath=artifacts/coverage/lcov.info"
            NODE_OPTIONS: "--max_old_space_size=8192"
        requires: [~pr, ~commit]
        steps:
            - install: npm install
            - test: npm test

    publish:
        requires: main
        template: screwdriver-cd/semantic-release
        secrets:
            # Publishing to NPM
            - NPM_TOKEN
            # Pushing tags to Git
            - GH_TOKEN
