shared:
    image: node:6

jobs:
    main:
        steps:
            - set: meta set dirs[0].foo true
            - set2: meta set dirs[1].bar false
    publish:
        steps:
            - get: meta get dirs
