shared:
    image: node:6

jobs:
    main:
        steps:
            - write-file: echo "hello" > $SD_ARTIFACTS_DIR/test
            - read-file: cat $SD_ARTIFACTS_DIR/test
            - curl: response=curl -X PUT https://store.screwdriver.cd/v1/builds/1101/mytest -d $SD_ARTIFACTS_DIR/test
            - response: echo $response
